image: sntshk/ubuntu:nunet

stages:
  - test
  - build

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - go test -cover ./...

lint-test-job:
  stage: test
  script:
    - echo "Linting go code..."
    - go vet ./...

build-job:
  stage: build
  script:
    - echo "Building debian archives..."
    - bash maint-scripts/build.sh

