// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: service_spec/cardano.proto

package nunet_cardano_access

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CardanoClient is the client API for Cardano service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardanoClient interface {
	Run(ctx context.Context, in *CommandInputs, opts ...grpc.CallOption) (*ResultOutput, error)
}

type cardanoClient struct {
	cc grpc.ClientConnInterface
}

func NewCardanoClient(cc grpc.ClientConnInterface) CardanoClient {
	return &cardanoClient{cc}
}

func (c *cardanoClient) Run(ctx context.Context, in *CommandInputs, opts ...grpc.CallOption) (*ResultOutput, error) {
	out := new(ResultOutput)
	err := c.cc.Invoke(ctx, "/Cardano/run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardanoServer is the server API for Cardano service.
// All implementations must embed UnimplementedCardanoServer
// for forward compatibility
type CardanoServer interface {
	Run(context.Context, *CommandInputs) (*ResultOutput, error)
	mustEmbedUnimplementedCardanoServer()
}

// UnimplementedCardanoServer must be embedded to have forward compatible implementations.
type UnimplementedCardanoServer struct {
}

func (UnimplementedCardanoServer) Run(context.Context, *CommandInputs) (*ResultOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedCardanoServer) mustEmbedUnimplementedCardanoServer() {}

// UnsafeCardanoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardanoServer will
// result in compilation errors.
type UnsafeCardanoServer interface {
	mustEmbedUnimplementedCardanoServer()
}

func RegisterCardanoServer(s grpc.ServiceRegistrar, srv CardanoServer) {
	s.RegisterService(&Cardano_ServiceDesc, srv)
}

func _Cardano_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandInputs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardanoServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cardano/run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardanoServer).Run(ctx, req.(*CommandInputs))
	}
	return interceptor(ctx, in, info, handler)
}

// Cardano_ServiceDesc is the grpc.ServiceDesc for Cardano service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cardano_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Cardano",
	HandlerType: (*CardanoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "run",
			Handler:    _Cardano_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_spec/cardano.proto",
}
