#!/bin/bash

echo Running postinst script.

USER=nunet

# if there is no such user, create it
adduser --system --no-create-home --quiet $USER
addgroup --system $USER
adduser $USER $USER

# Give above user access to write to /etc/nunet
chown -R $USER:$USER /etc/nunet

# Start the services.
systemctl daemon-reload
systemctl enable --now nunet-dms.service  # enable --now == enable and start
systemctl enable --now nomad-client.service

# https://unix.stackexchange.com/q/708286/22240
systemctl enable --now nomad-client-restart.path
