#!/bin/bash

echo Running postinst script.

USER=nunet

# if there is no such user, create it
adduser --system --quiet $USER
addgroup --system $USER
adduser $USER $USER
adduser $USER docker

# Give above user access to write to /etc/nunet
chown -R $USER:$USER /etc/nunet

# Start the services.
systemctl daemon-reload
systemctl enable --now nunet-dms.service  # enable --now == enable and start

# Add SUID on nunet-tap-config which is currently owned by root
# so that nunet user can run it without requiring password
chmod 4755 /usr/bin/nunet-tap-config

systemctl stop docker.service docker.socket
runuser -l $USER -c 'dockerd-rootless-setuptool.sh install --force'
systemctl start docker.service docker.socket
docker context use default

if command -v mandb > /dev/null; then
    echo Adding man page.
    mandb -q
fi
