#!/bin/bash

echo "Running pre installation script ..."

# Pre-install script for nunet-dms. 

# Part 1: Remove old version of nunet-dms.
# 0. Stop running service. Remove the service unit files.
# 1. Remove binary file.
# 2. Remove config files at /etc/nunet

echo "Stopping service and removing service unit files ..."

systemctl daemon-reload

if [ -f "/etc/systemd/system/nunet-dms.service" ];then
    systemctl stop nunet-dms.service
    rm /etc/systemd/system/nunet-dms.service
fi

echo "Looking for old versions of nunet-dms ..."

# XXX this can be removed once the new "nunet" binary has been in use for sometime
if [ -f "/usr/bin/nunet-dms" ];then
    rm -f /usr/bin/nunet-dms
    echo "Removed old nunet-dms binary from /usr/bin ..."
fi

if [ -f "/usr/bin/nunet" ];then
    rm -f /usr/bin/nunet
    echo "Removed old nunet binary from /usr/bin ..."
fi
