// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nunet_adapter.proto

package adapter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPeerParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPeerParams) Reset()         { *m = GetPeerParams{} }
func (m *GetPeerParams) String() string { return proto.CompactTextString(m) }
func (*GetPeerParams) ProtoMessage()    {}
func (*GetPeerParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{0}
}

func (m *GetPeerParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeerParams.Unmarshal(m, b)
}
func (m *GetPeerParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeerParams.Marshal(b, m, deterministic)
}
func (m *GetPeerParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeerParams.Merge(m, src)
}
func (m *GetPeerParams) XXX_Size() int {
	return xxx_messageInfo_GetPeerParams.Size(m)
}
func (m *GetPeerParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeerParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeerParams proto.InternalMessageInfo

type GetDhtParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDhtParams) Reset()         { *m = GetDhtParams{} }
func (m *GetDhtParams) String() string { return proto.CompactTextString(m) }
func (*GetDhtParams) ProtoMessage()    {}
func (*GetDhtParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{1}
}

func (m *GetDhtParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDhtParams.Unmarshal(m, b)
}
func (m *GetDhtParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDhtParams.Marshal(b, m, deterministic)
}
func (m *GetDhtParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDhtParams.Merge(m, src)
}
func (m *GetDhtParams) XXX_Size() int {
	return xxx_messageInfo_GetDhtParams.Size(m)
}
func (m *GetDhtParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDhtParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetDhtParams proto.InternalMessageInfo

type Peers struct {
	PeerAddress          string   `protobuf:"bytes,1,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peers) Reset()         { *m = Peers{} }
func (m *Peers) String() string { return proto.CompactTextString(m) }
func (*Peers) ProtoMessage()    {}
func (*Peers) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{2}
}

func (m *Peers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peers.Unmarshal(m, b)
}
func (m *Peers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peers.Marshal(b, m, deterministic)
}
func (m *Peers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peers.Merge(m, src)
}
func (m *Peers) XXX_Size() int {
	return xxx_messageInfo_Peers.Size(m)
}
func (m *Peers) XXX_DiscardUnknown() {
	xxx_messageInfo_Peers.DiscardUnknown(m)
}

var xxx_messageInfo_Peers proto.InternalMessageInfo

func (m *Peers) GetPeerAddress() string {
	if m != nil {
		return m.PeerAddress
	}
	return ""
}

type NodeID struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeID) Reset()         { *m = NodeID{} }
func (m *NodeID) String() string { return proto.CompactTextString(m) }
func (*NodeID) ProtoMessage()    {}
func (*NodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{3}
}

func (m *NodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeID.Unmarshal(m, b)
}
func (m *NodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeID.Marshal(b, m, deterministic)
}
func (m *NodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeID.Merge(m, src)
}
func (m *NodeID) XXX_Size() int {
	return xxx_messageInfo_NodeID.Size(m)
}
func (m *NodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeID.DiscardUnknown(m)
}

var xxx_messageInfo_NodeID proto.InternalMessageInfo

func (m *NodeID) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type DHTUpdateContent struct {
	HasGpu               string   `protobuf:"bytes,1,opt,name=has_gpu,json=hasGpu,proto3" json:"has_gpu,omitempty"`
	AllowCardano         string   `protobuf:"bytes,2,opt,name=allow_cardano,json=allowCardano,proto3" json:"allow_cardano,omitempty"`
	GpuInfo              string   `protobuf:"bytes,3,opt,name=gpu_info,json=gpuInfo,proto3" json:"gpu_info,omitempty"`
	ServicesIndex        string   `protobuf:"bytes,4,opt,name=services_index,json=servicesIndex,proto3" json:"services_index,omitempty"`
	AvailableResources   string   `protobuf:"bytes,5,opt,name=available_resources,json=availableResources,proto3" json:"available_resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DHTUpdateContent) Reset()         { *m = DHTUpdateContent{} }
func (m *DHTUpdateContent) String() string { return proto.CompactTextString(m) }
func (*DHTUpdateContent) ProtoMessage()    {}
func (*DHTUpdateContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{4}
}

func (m *DHTUpdateContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHTUpdateContent.Unmarshal(m, b)
}
func (m *DHTUpdateContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHTUpdateContent.Marshal(b, m, deterministic)
}
func (m *DHTUpdateContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHTUpdateContent.Merge(m, src)
}
func (m *DHTUpdateContent) XXX_Size() int {
	return xxx_messageInfo_DHTUpdateContent.Size(m)
}
func (m *DHTUpdateContent) XXX_DiscardUnknown() {
	xxx_messageInfo_DHTUpdateContent.DiscardUnknown(m)
}

var xxx_messageInfo_DHTUpdateContent proto.InternalMessageInfo

func (m *DHTUpdateContent) GetHasGpu() string {
	if m != nil {
		return m.HasGpu
	}
	return ""
}

func (m *DHTUpdateContent) GetAllowCardano() string {
	if m != nil {
		return m.AllowCardano
	}
	return ""
}

func (m *DHTUpdateContent) GetGpuInfo() string {
	if m != nil {
		return m.GpuInfo
	}
	return ""
}

func (m *DHTUpdateContent) GetServicesIndex() string {
	if m != nil {
		return m.ServicesIndex
	}
	return ""
}

func (m *DHTUpdateContent) GetAvailableResources() string {
	if m != nil {
		return m.AvailableResources
	}
	return ""
}

type DHTUpdateResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DHTUpdateResponse) Reset()         { *m = DHTUpdateResponse{} }
func (m *DHTUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*DHTUpdateResponse) ProtoMessage()    {}
func (*DHTUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{5}
}

func (m *DHTUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DHTUpdateResponse.Unmarshal(m, b)
}
func (m *DHTUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DHTUpdateResponse.Marshal(b, m, deterministic)
}
func (m *DHTUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DHTUpdateResponse.Merge(m, src)
}
func (m *DHTUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_DHTUpdateResponse.Size(m)
}
func (m *DHTUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DHTUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DHTUpdateResponse proto.InternalMessageInfo

func (m *DHTUpdateResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type DhtContents struct {
	MachinesIndex           string   `protobuf:"bytes,1,opt,name=machines_index,json=machinesIndex,proto3" json:"machines_index,omitempty"`
	AvailableResourcesIndex string   `protobuf:"bytes,2,opt,name=available_resources_index,json=availableResourcesIndex,proto3" json:"available_resources_index,omitempty"`
	ServicesIndex           string   `protobuf:"bytes,3,opt,name=services_index,json=servicesIndex,proto3" json:"services_index,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *DhtContents) Reset()         { *m = DhtContents{} }
func (m *DhtContents) String() string { return proto.CompactTextString(m) }
func (*DhtContents) ProtoMessage()    {}
func (*DhtContents) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{6}
}

func (m *DhtContents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DhtContents.Unmarshal(m, b)
}
func (m *DhtContents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DhtContents.Marshal(b, m, deterministic)
}
func (m *DhtContents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DhtContents.Merge(m, src)
}
func (m *DhtContents) XXX_Size() int {
	return xxx_messageInfo_DhtContents.Size(m)
}
func (m *DhtContents) XXX_DiscardUnknown() {
	xxx_messageInfo_DhtContents.DiscardUnknown(m)
}

var xxx_messageInfo_DhtContents proto.InternalMessageInfo

func (m *DhtContents) GetMachinesIndex() string {
	if m != nil {
		return m.MachinesIndex
	}
	return ""
}

func (m *DhtContents) GetAvailableResourcesIndex() string {
	if m != nil {
		return m.AvailableResourcesIndex
	}
	return ""
}

func (m *DhtContents) GetServicesIndex() string {
	if m != nil {
		return m.ServicesIndex
	}
	return ""
}

type MessageParams struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	MessageContent       string   `protobuf:"bytes,2,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageParams) Reset()         { *m = MessageParams{} }
func (m *MessageParams) String() string { return proto.CompactTextString(m) }
func (*MessageParams) ProtoMessage()    {}
func (*MessageParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{7}
}

func (m *MessageParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageParams.Unmarshal(m, b)
}
func (m *MessageParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageParams.Marshal(b, m, deterministic)
}
func (m *MessageParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageParams.Merge(m, src)
}
func (m *MessageParams) XXX_Size() int {
	return xxx_messageInfo_MessageParams.Size(m)
}
func (m *MessageParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageParams.DiscardUnknown(m)
}

var xxx_messageInfo_MessageParams proto.InternalMessageInfo

func (m *MessageParams) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *MessageParams) GetMessageContent() string {
	if m != nil {
		return m.MessageContent
	}
	return ""
}

type MessageResponse struct {
	MessageResponse      string   `protobuf:"bytes,1,opt,name=message_response,json=messageResponse,proto3" json:"message_response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{8}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetMessageResponse() string {
	if m != nil {
		return m.MessageResponse
	}
	return ""
}

type GetPkey struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPkey) Reset()         { *m = GetPkey{} }
func (m *GetPkey) String() string { return proto.CompactTextString(m) }
func (*GetPkey) ProtoMessage()    {}
func (*GetPkey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{9}
}

func (m *GetPkey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPkey.Unmarshal(m, b)
}
func (m *GetPkey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPkey.Marshal(b, m, deterministic)
}
func (m *GetPkey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPkey.Merge(m, src)
}
func (m *GetPkey) XXX_Size() int {
	return xxx_messageInfo_GetPkey.Size(m)
}
func (m *GetPkey) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPkey.DiscardUnknown(m)
}

var xxx_messageInfo_GetPkey proto.InternalMessageInfo

type Pkey struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pkey) Reset()         { *m = Pkey{} }
func (m *Pkey) String() string { return proto.CompactTextString(m) }
func (*Pkey) ProtoMessage()    {}
func (*Pkey) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{10}
}

func (m *Pkey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pkey.Unmarshal(m, b)
}
func (m *Pkey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pkey.Marshal(b, m, deterministic)
}
func (m *Pkey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pkey.Merge(m, src)
}
func (m *Pkey) XXX_Size() int {
	return xxx_messageInfo_Pkey.Size(m)
}
func (m *Pkey) XXX_DiscardUnknown() {
	xxx_messageInfo_Pkey.DiscardUnknown(m)
}

var xxx_messageInfo_Pkey proto.InternalMessageInfo

func (m *Pkey) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type ReceivedMessageParams struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceivedMessageParams) Reset()         { *m = ReceivedMessageParams{} }
func (m *ReceivedMessageParams) String() string { return proto.CompactTextString(m) }
func (*ReceivedMessageParams) ProtoMessage()    {}
func (*ReceivedMessageParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5db5ca0d15008a7, []int{11}
}

func (m *ReceivedMessageParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceivedMessageParams.Unmarshal(m, b)
}
func (m *ReceivedMessageParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceivedMessageParams.Marshal(b, m, deterministic)
}
func (m *ReceivedMessageParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceivedMessageParams.Merge(m, src)
}
func (m *ReceivedMessageParams) XXX_Size() int {
	return xxx_messageInfo_ReceivedMessageParams.Size(m)
}
func (m *ReceivedMessageParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceivedMessageParams.DiscardUnknown(m)
}

var xxx_messageInfo_ReceivedMessageParams proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetPeerParams)(nil), "getPeerParams")
	proto.RegisterType((*GetDhtParams)(nil), "getDhtParams")
	proto.RegisterType((*Peers)(nil), "peers")
	proto.RegisterType((*NodeID)(nil), "nodeID")
	proto.RegisterType((*DHTUpdateContent)(nil), "DHTUpdateContent")
	proto.RegisterType((*DHTUpdateResponse)(nil), "DHTUpdateResponse")
	proto.RegisterType((*DhtContents)(nil), "DhtContents")
	proto.RegisterType((*MessageParams)(nil), "messageParams")
	proto.RegisterType((*MessageResponse)(nil), "messageResponse")
	proto.RegisterType((*GetPkey)(nil), "getPkey")
	proto.RegisterType((*Pkey)(nil), "Pkey")
	proto.RegisterType((*ReceivedMessageParams)(nil), "receivedMessageParams")
}

func init() { proto.RegisterFile("nunet_adapter.proto", fileDescriptor_f5db5ca0d15008a7) }

var fileDescriptor_f5db5ca0d15008a7 = []byte{
	// 612 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6e, 0x13, 0x3d,
	0x10, 0x4d, 0xbe, 0xfe, 0xa4, 0x99, 0xfc, 0xb5, 0xae, 0x3e, 0x9a, 0x46, 0x42, 0xa2, 0x46, 0x55,
	0x0b, 0x52, 0x1d, 0x28, 0xbd, 0x42, 0x20, 0x54, 0x1a, 0x89, 0x56, 0x50, 0x54, 0x4a, 0xb9, 0xe1,
	0x66, 0xe5, 0xec, 0x4e, 0x37, 0xab, 0xee, 0xda, 0x2b, 0xdb, 0x5b, 0xe8, 0x93, 0x70, 0xc7, 0xcb,
	0xf0, 0x62, 0x68, 0x6d, 0x27, 0xa4, 0x49, 0xb8, 0xe1, 0x6a, 0xed, 0x33, 0x33, 0xda, 0x39, 0x67,
	0xce, 0x18, 0x36, 0x45, 0x21, 0xd0, 0x04, 0x3c, 0xe2, 0xb9, 0x41, 0xc5, 0x72, 0x25, 0x8d, 0xa4,
	0x1d, 0x68, 0xc5, 0x68, 0x2e, 0x10, 0xd5, 0x05, 0x57, 0x3c, 0xd3, 0xb4, 0x0d, 0xcd, 0x18, 0xcd,
	0x60, 0x64, 0xfc, 0xfd, 0x29, 0xac, 0xe4, 0x88, 0x4a, 0x93, 0x1d, 0x68, 0x96, 0x87, 0x80, 0x47,
	0x91, 0x42, 0xad, 0xbb, 0xd5, 0x47, 0xd5, 0xfd, 0xfa, 0x65, 0xa3, 0xc4, 0x8e, 0x1d, 0x44, 0x77,
	0x60, 0x55, 0xc8, 0x08, 0xcf, 0x06, 0x64, 0x0b, 0x6a, 0xe5, 0x29, 0x48, 0x22, 0x9f, 0xe7, 0x02,
	0x11, 0xfd, 0x55, 0x85, 0xf5, 0xc1, 0xe9, 0xd5, 0x97, 0x3c, 0xe2, 0x06, 0x4f, 0xa4, 0x30, 0x28,
	0x4c, 0x99, 0x3d, 0xe2, 0x3a, 0x88, 0xf3, 0x62, 0x9c, 0x3d, 0xe2, 0xfa, 0x5d, 0x5e, 0x90, 0xc7,
	0xd0, 0xe2, 0x69, 0x2a, 0xbf, 0x05, 0x21, 0x57, 0x11, 0x17, 0xb2, 0xfb, 0x9f, 0x0d, 0x37, 0x2d,
	0x78, 0xe2, 0x30, 0xb2, 0x0d, 0x6b, 0x71, 0x5e, 0x04, 0x89, 0xb8, 0x96, 0xdd, 0x25, 0x1b, 0xaf,
	0xc5, 0x79, 0x71, 0x26, 0xae, 0x25, 0xd9, 0x85, 0xb6, 0x46, 0x75, 0x9b, 0x84, 0xa8, 0x83, 0x44,
	0x44, 0xf8, 0xbd, 0xbb, 0x6c, 0x13, 0x5a, 0x63, 0xf4, 0xac, 0x04, 0x49, 0x1f, 0x36, 0xf9, 0x2d,
	0x4f, 0x52, 0x3e, 0x4c, 0x31, 0x50, 0xa8, 0x65, 0xa1, 0x42, 0xd4, 0xdd, 0x15, 0x9b, 0x4b, 0x26,
	0xa1, 0xcb, 0x71, 0x84, 0xf6, 0x61, 0x63, 0x42, 0xe2, 0x12, 0x75, 0x2e, 0x85, 0x46, 0xd2, 0x83,
	0x35, 0xe5, 0xcf, 0x9e, 0xc6, 0xe4, 0x4e, 0x7f, 0x54, 0xa1, 0x31, 0x18, 0x19, 0x4f, 0x58, 0x97,
	0x8d, 0x65, 0x3c, 0x1c, 0x25, 0x62, 0xd2, 0x98, 0xab, 0x68, 0x8d, 0x51, 0xd7, 0xd8, 0x4b, 0xd8,
	0x5e, 0xd0, 0x98, 0xaf, 0x70, 0x5a, 0x6c, 0xcd, 0xb7, 0xe7, 0x6a, 0xe7, 0xb9, 0x2f, 0x2d, 0xe0,
	0x4e, 0x3f, 0x41, 0x2b, 0x43, 0xad, 0x79, 0x8c, 0x6e, 0xe0, 0x7f, 0x1d, 0x1d, 0xd9, 0x83, 0x8e,
	0xcf, 0x0c, 0x42, 0xc7, 0xc3, 0xb7, 0xd0, 0xf6, 0xb0, 0x67, 0x47, 0x5f, 0x4d, 0x12, 0x27, 0xda,
	0x3c, 0x81, 0xf5, 0x71, 0xed, 0x8c, 0x46, 0xb3, 0xa9, 0xb4, 0x0e, 0xb5, 0xd2, 0x91, 0x37, 0x78,
	0x47, 0x77, 0x61, 0xb9, 0xfc, 0x92, 0x87, 0x00, 0x79, 0x31, 0x4c, 0x93, 0x30, 0xb8, 0xc1, 0x3b,
	0x5f, 0x57, 0x77, 0xc8, 0x7b, 0xbc, 0xa3, 0x5b, 0xf0, 0xbf, 0xc2, 0x10, 0x93, 0x5b, 0x8c, 0xce,
	0xa7, 0xa9, 0x1c, 0xfe, 0x5c, 0x82, 0xe6, 0xc7, 0xd2, 0xf4, 0xc7, 0xce, 0xf3, 0x64, 0x0f, 0x1a,
	0xde, 0xed, 0x1f, 0x12, 0x6d, 0x48, 0x9b, 0xdd, 0xf3, 0x7e, 0x6f, 0x95, 0x59, 0xab, 0xd3, 0x0a,
	0x61, 0x76, 0x2d, 0xfe, 0x4c, 0x8c, 0xb4, 0xd8, 0xf4, 0x56, 0xf4, 0x9a, 0x6c, 0x6a, 0x9a, 0xb4,
	0x42, 0x9e, 0x43, 0x43, 0xa3, 0x18, 0xff, 0x9e, 0xb4, 0xd9, 0x3d, 0x4d, 0x7b, 0xeb, 0x6c, 0x96,
	0x65, 0x85, 0xbc, 0x86, 0xce, 0x4c, 0xd7, 0xe4, 0x01, 0x5b, 0xc8, 0x63, 0x61, 0xf9, 0x1b, 0xe8,
	0x24, 0x22, 0x94, 0x59, 0x22, 0xe2, 0x7f, 0x28, 0x7f, 0x56, 0x25, 0xfb, 0x56, 0x8b, 0xcf, 0x98,
	0x5e, 0x97, 0x0a, 0xcc, 0x69, 0x51, 0x63, 0x6e, 0x95, 0x69, 0x85, 0x1c, 0x41, 0xbd, 0xb0, 0x56,
	0x1f, 0x9c, 0x5e, 0x91, 0x0d, 0x36, 0xbb, 0xbe, 0x3d, 0xc2, 0xe6, 0x96, 0x81, 0x56, 0x08, 0xb5,
	0x12, 0x9e, 0x73, 0x6d, 0x50, 0xd9, 0x29, 0xae, 0x31, 0x3f, 0xd7, 0xde, 0x0a, 0xb3, 0xe3, 0xad,
	0xbc, 0x3d, 0xfa, 0x7a, 0x18, 0x27, 0x26, 0xe5, 0x43, 0x16, 0xca, 0xac, 0x6f, 0xdf, 0xa7, 0x7e,
	0x84, 0xa5, 0x3b, 0x0f, 0x32, 0x2e, 0x78, 0x8c, 0x19, 0x0a, 0x73, 0xe0, 0x0d, 0xdb, 0xf7, 0x2f,
	0xd7, 0x70, 0xd5, 0x3e, 0x5d, 0x2f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x1f, 0xcf, 0x97,
	0xd1, 0x04, 0x00, 0x00,
}
