// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: specs/compute-api-spec/oracle.proto

package oracle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FundingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FundingRequest) Reset() {
	*x = FundingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_specs_compute_api_spec_oracle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FundingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingRequest) ProtoMessage() {}

func (x *FundingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_compute_api_spec_oracle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingRequest.ProtoReflect.Descriptor instead.
func (*FundingRequest) Descriptor() ([]byte, []int) {
	return file_specs_compute_api_spec_oracle_proto_rawDescGZIP(), []int{0}
}

type FundingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature     string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	OracleMessage string `protobuf:"bytes,2,opt,name=oracle_message,json=oracleMessage,proto3" json:"oracle_message,omitempty"`
}

func (x *FundingResponse) Reset() {
	*x = FundingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_specs_compute_api_spec_oracle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FundingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingResponse) ProtoMessage() {}

func (x *FundingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_compute_api_spec_oracle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingResponse.ProtoReflect.Descriptor instead.
func (*FundingResponse) Descriptor() ([]byte, []int) {
	return file_specs_compute_api_spec_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *FundingResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *FundingResponse) GetOracleMessage() string {
	if x != nil {
		return x.OracleMessage
	}
	return ""
}

type WithdrawRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *job_duration in minutes
	JobStatus            string `protobuf:"bytes,1,opt,name=job_status,json=jobStatus,proto3" json:"job_status,omitempty"`
	JobDuration          int64  `protobuf:"varint,2,opt,name=job_duration,json=jobDuration,proto3" json:"job_duration,omitempty"`
	EstimatedJobDuration int64  `protobuf:"varint,3,opt,name=estimated_job_duration,json=estimatedJobDuration,proto3" json:"estimated_job_duration,omitempty"`
	LogPath              string `protobuf:"bytes,4,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_specs_compute_api_spec_oracle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_specs_compute_api_spec_oracle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_specs_compute_api_spec_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *WithdrawRequest) GetJobStatus() string {
	if x != nil {
		return x.JobStatus
	}
	return ""
}

func (x *WithdrawRequest) GetJobDuration() int64 {
	if x != nil {
		return x.JobDuration
	}
	return 0
}

func (x *WithdrawRequest) GetEstimatedJobDuration() int64 {
	if x != nil {
		return x.EstimatedJobDuration
	}
	return 0
}

func (x *WithdrawRequest) GetLogPath() string {
	if x != nil {
		return x.LogPath
	}
	return ""
}

type WithdrawResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature     string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	OracleMessage string `protobuf:"bytes,2,opt,name=oracle_message,json=oracleMessage,proto3" json:"oracle_message,omitempty"`
	RewardType    string `protobuf:"bytes,3,opt,name=reward_type,json=rewardType,proto3" json:"reward_type,omitempty"`
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_specs_compute_api_spec_oracle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_specs_compute_api_spec_oracle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponse.ProtoReflect.Descriptor instead.
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_specs_compute_api_spec_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *WithdrawResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WithdrawResponse) GetOracleMessage() string {
	if x != nil {
		return x.OracleMessage
	}
	return ""
}

func (x *WithdrawResponse) GetRewardType() string {
	if x != nil {
		return x.RewardType
	}
	return ""
}

var File_specs_compute_api_spec_oracle_proto protoreflect.FileDescriptor

var file_specs_compute_api_spec_oracle_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x70, 0x65, 0x63, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x2d,
	0x61, 0x70, 0x69, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x22, 0x10, 0x0a,
	0x0e, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x56, 0x0a, 0x0f, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa4, 0x01, 0x0a, 0x0f, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6a,
	0x6f, 0x62, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6a, 0x6f, 0x62, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6a, 0x6f,
	0x62, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x6a, 0x6f, 0x62, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a,
	0x16, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6a, 0x6f, 0x62, 0x5f, 0x64,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x65,
	0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x4a, 0x6f, 0x62, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x50, 0x61, 0x74, 0x68, 0x22, 0x78,
	0x0a, 0x10, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x32, 0x9d, 0x01, 0x0a, 0x06, 0x4f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x12, 0x47, 0x0a, 0x12, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x2e, 0x6f, 0x72, 0x61, 0x63,
	0x6c, 0x65, 0x2e, 0x46, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x46, 0x75, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x13,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x52, 0x65, 0x71, 0x12, 0x17, 0x2e, 0x6f, 0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6f,
	0x72, 0x61, 0x63, 0x6c, 0x65, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x6f, 0x72, 0x61,
	0x63, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_specs_compute_api_spec_oracle_proto_rawDescOnce sync.Once
	file_specs_compute_api_spec_oracle_proto_rawDescData = file_specs_compute_api_spec_oracle_proto_rawDesc
)

func file_specs_compute_api_spec_oracle_proto_rawDescGZIP() []byte {
	file_specs_compute_api_spec_oracle_proto_rawDescOnce.Do(func() {
		file_specs_compute_api_spec_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(file_specs_compute_api_spec_oracle_proto_rawDescData)
	})
	return file_specs_compute_api_spec_oracle_proto_rawDescData
}

var file_specs_compute_api_spec_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_specs_compute_api_spec_oracle_proto_goTypes = []interface{}{
	(*FundingRequest)(nil),   // 0: oracle.FundingRequest
	(*FundingResponse)(nil),  // 1: oracle.FundingResponse
	(*WithdrawRequest)(nil),  // 2: oracle.WithdrawRequest
	(*WithdrawResponse)(nil), // 3: oracle.WithdrawResponse
}
var file_specs_compute_api_spec_oracle_proto_depIdxs = []int32{
	0, // 0: oracle.Oracle.ValidateFundingReq:input_type -> oracle.FundingRequest
	2, // 1: oracle.Oracle.ValidateWithdrawReq:input_type -> oracle.WithdrawRequest
	1, // 2: oracle.Oracle.ValidateFundingReq:output_type -> oracle.FundingResponse
	3, // 3: oracle.Oracle.ValidateWithdrawReq:output_type -> oracle.WithdrawResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_specs_compute_api_spec_oracle_proto_init() }
func file_specs_compute_api_spec_oracle_proto_init() {
	if File_specs_compute_api_spec_oracle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_specs_compute_api_spec_oracle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FundingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_specs_compute_api_spec_oracle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FundingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_specs_compute_api_spec_oracle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_specs_compute_api_spec_oracle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_specs_compute_api_spec_oracle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_specs_compute_api_spec_oracle_proto_goTypes,
		DependencyIndexes: file_specs_compute_api_spec_oracle_proto_depIdxs,
		MessageInfos:      file_specs_compute_api_spec_oracle_proto_msgTypes,
	}.Build()
	File_specs_compute_api_spec_oracle_proto = out.File
	file_specs_compute_api_spec_oracle_proto_rawDesc = nil
	file_specs_compute_api_spec_oracle_proto_goTypes = nil
	file_specs_compute_api_spec_oracle_proto_depIdxs = nil
}
