basePath: /api/v1
definitions:
  models.AddressPrivKey:
    properties:
      address:
        type: string
      private_key:
        type: string
    type: object
  models.Metadata:
    properties:
      available:
        properties:
          ram:
            type: integer
          update_timestamp:
            type: integer
        type: object
      name:
        type: string
      network:
        type: string
      public_key:
        type: string
      reserved:
        properties:
          cpu:
            type: integer
          memory:
            type: integer
        type: object
      resource:
        properties:
          cpu_max:
            type: number
          cpu_usage:
            type: number
          ram_max:
            type: integer
          total_core:
            type: integer
          update_timestamp:
            type: integer
        type: object
    type: object
  models.Provisioned:
    properties:
      cpu:
        type: number
      memory:
        type: integer
      total_cores:
        type: integer
    type: object
host: localhost:9999
info:
  contact:
    email: support@nunet.io
    name: Support
    url: https://devexchange.nunet.io/
  description: A dashboard application for computing providers.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://nunet.io/tos
  title: Device Management Service
  version: 0.4.15
paths:
  /free:
    get:
      description: Checks and returns the amount of free resources available
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Returns the amount of free resources available
      tags:
      - telemetry
  /onboarding/address/new:
    get:
      description: Create a payment address from public key. Return payment address
        and private key.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AddressPrivKey'
      summary: Create a new payment address.
      tags:
      - onboarding
  /onboarding/metadata:
    get:
      description: Responds with metadata of current provideer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Metadata'
            type: array
      summary: Get current device info.
      tags:
      - onboarding
  /onboarding/onboard:
    post:
      description: Onboard runs onboarding script given the amount of resources to
        onboard.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Metadata'
            type: array
      summary: Runs the onboarding process.
      tags:
      - onboarding
  /onboarding/provisioned:
    get:
      description: Get total memory capacity in MB and CPU capacity in MHz.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Provisioned'
      summary: Returns provisioned capacity on host.
      tags:
      - onboarding
  /peers/list:
    get:
      description: Gets a list of peers the adapter can see within the network and
        return a list of peer info
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Return list of peers currently connected to
      tags:
      - run
  /peers/ws:
    get:
      description: Sends a command to specific node and prints back response.
      responses:
        "200":
          description: OK
      summary: Sends a command to specific node and prints back response.
      tags:
      - peers
  /run/deploy:
    post:
      description: SendDeploymentRequest searches the DHT for non-busy, available
        devices with appropriate metadata. Then sends a deployment request to the
        first machine
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Search devices on DHT with appropriate machines and sends a deployment
        request.
      tags:
      - run
  /vm/start-custom:
    post:
      description: This endpoint is an abstraction of all primitive endpoints. When
        invokend, it calls all primitive endpoints in a sequence.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Start a VM with custom configuration.
      tags:
      - vm
  /vm/start-default:
    post:
      description: Everything except kernel files and filesystem file will be set
        by DMS itself.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Start a VM with default configuration.
      tags:
      - vm
swagger: "2.0"
