#!/bin/bash

linux_distro=$(grep -Po "(?<=^ID=).+" /etc/os-release | sed 's/"//g') # we add support for specific linux distributions through this variable.

secure_boot_check
printf "${INFO_C}-----Starting AMD GPU Driver Installation-----${NORMAL_C}\n"
if [[ $linux_distro = "ubuntu" ]]; then
    sudo apt update
    # Detect the Ubuntu version
    ubuntu_version=$(lsb_release -sr)
    # Install the correct AMD GPU driver based on the Ubuntu version

    if [ "$ubuntu_version" == "20.04" ]; then
        sleep 1 # without this, text from the "apt update" output may get overlapped with the below line when printing
        printf "${INFO_C}Detected Ubuntu 20.04. Installing AMDGPU ROCm Driver 5.5...${NORMAL_C}"
        wget https://repo.radeon.com/amdgpu-install/5.5/ubuntu/focal/amdgpu-install_5.5.50500-1_all.deb 
        sudo apt install ./amdgpu-install_5.5.50500-1_all.deb
        sudo amdgpu-install --usecase=rocm            
        rm -rf amdgpu-install_5.5.50500-1_all.deb
        sudo usermod -a -G video $LOGNAME
        sudo usermod -a -G render $LOGNAME
    elif [ "$ubuntu_version" == "22.04" ]; then
        sleep 1 # without this, text from the "apt update" output may get overlapped with the below line when printing
        printf "${INFO_C}Detected Ubuntu 22.04. Installing AMDGPU ROCm Driver 5.5...${NORMAL_C}"
        wget https://repo.radeon.com/amdgpu-install/5.5/ubuntu/jammy/amdgpu-install_5.5.50500-1_all.deb 
        sudo apt install ./amdgpu-install_5.5.50500-1_all.deb
        sudo amdgpu-install --usecase=rocm            
        rm -rf amdgpu-install_5.5.50500-1_all.deb
        sudo usermod -a -G video $LOGNAME
        sudo usermod -a -G render $LOGNAME
    else
        printf "${BAD_C}Unsupported Ubuntu version: $ubuntu_version${NORMAL_C}"
    fi

    gpu_driver_version="$(rocm-smi --showdriverversion 2>/dev/null | grep 'Driver version' | awk '{print $3}')"

    if [[ -n $gpu_driver_version ]]; then
        printf "${GOOD_C}-----AMDGPU driver version: $gpu_driver_version Installed-----${NORMAL_C}\n"
    else
        printf "${BAD_C}-----AMDGPU Driver Not Found. Please Reboot and Retry-----${NORMAL_C}\n"
    fi

else
    printf "${INFO_C}Currently, only Ubuntu Distributions are supported. But we will definitely try to add support for more distros in future.${NORMAL_C}\n"
fi
