#!/bin/bash

linux_distro=$(grep -Po "(?<=^ID=).+" /etc/os-release | sed 's/"//g') # we add support for specific linux distributions through this variable.

secure_boot_check
printf "${INFO_C}-----Starting NVIDIA GPU Driver Installation-----${NORMAL_C}\n"
if [[ $linux_distro = "ubuntu" ]]; then
    sudo apt update
    # Detect the Ubuntu version
    ubuntu_version=$(lsb_release -sr)
    # Install the correct NVIDIA driver based on the Ubuntu version
    if [ "$ubuntu_version" == "18.04" ]; then
        sleep 1 # without this, text from the "apt update" output may get overlapped with the below line when printing
        printf "${INFO_C}Detected Ubuntu 18.04. Installing NVIDIA Driver Series 520...${NORMAL_C}"
        sudo apt install nvidia-driver-525 # may change later based on ML functionality/performance
    elif [ "$ubuntu_version" == "20.04" ]; then
        sleep 1 # without this, text from the "apt update" output may get overlapped with the below line when printing
        printf "${INFO_C}Detected Ubuntu 20.04. Installing NVIDIA Driver Series 520...${NORMAL_C}"
        sudo apt install nvidia-driver-525 # may change later based on ML functionality/performance
    elif [ "$ubuntu_version" == "22.04" ]; then
        sleep 1 # without this, text from the "apt update" output may get overlapped with the below line when printing
        printf "${INFO_C}Detected Ubuntu 22.04. Installing NVIDIA Driver Series 520...${NORMAL_C}"
        sudo apt install nvidia-driver-525 # may change later based on ML functionality/performance
    else
        printf "${BAD_C}Unsupported Ubuntu version: $ubuntu_version${NORMAL_C}"
    fi
    gpu_driver_version="$(nvidia-smi 2>/dev/null | grep Driver | awk '{print "NVIDIA " $4 " " $5 " " $6}')" # the gpu driver version
    gpu_driver_var="$(nvidia-smi 2>/dev/null | grep Driver | awk '{print $4}')" # a variable with value "Driver"

    if [[ $gpu_driver_var = "Driver" ]]; then
        printf "${GOOD_C}-----NVIDIA GPU Driver $gpu_driver_version Installed-----${NORMAL_C}\n"
    else
        printf "${BAD_C}-----NVIDIA GPU Driver Still Not Found. Please Reboot and Retry-----${NORMAL_C}\n"
    fi

elif [[ $linux_distro = "kali" ]]; then
    sudo apt update && sudo apt install -y nvidia-driver
    gpu_driver_var="$(nvidia-smi 2>/dev/null | grep Driver | awk '{print $4}')"
    gpu_driver_version="$(nvidia-smi 2>/dev/null | grep Driver | awk '{print "NVIDIA " $4 " " $5 " " $6}')"

    if [[ $gpu_driver_var = "Driver" ]]; then
        printf "${GOOD_C}-----NVIDIA GPU Driver $gpu_driver_version Installed-----${NORMAL_C}\n"
    else
        printf "${BAD_C}-----NVIDIA GPU Driver Still Not Found. Please Reboot and Retry-----${NORMAL_C}\n"
    fi
else
    printf "${INFO_C}Currently, only Ubuntu and Kali Linux Distributions are supported. But we will definitely add support for more distros in future.${NORMAL_C}\n"
fi
